//decks: ['JLPT N2 Verbs', 'JLPT N2 Adjectives', 'Genki 1', 'Genki 2', 'Business Japanese']

var decks = [
  {
    username: 'kaijuking',
    deckname: 'JLPT N2 Verbs',
    source: 'ニュースの日本語',
    isbn: '978-4-7890-1596-7',
    publisher: 'The Japan Times',
    numcards: 2,
    description: 'A list of JLPT N2 verbs',
    createdon: 1459288218005,
    lastmodified: 1459288218005,
    cards: [{id: 1, word: '食べる', pronunciation: 'たべる', meaning: 'to eat', type: 'ru-verb'},
            {id: 2, word: '食べる', pronunciation: 'たべる', meaning: 'to eat', type: 'ru-verb'}]
  },
  {
    username: 'kaijuking',
    deckname: 'JLPT N2 Adjectives',
    source: 'ニュースの日本語',
    isbn: '978-4-7890-1596-7',
    publisher: 'The Japan Times',
    numcards: 2,
    description: 'A list of JLPT N2 adjectives',
    createdon: 1459288235927,
    lastmodified: 1459288235927,
    cards: [{id: 1, word: '飲む', pronunciation: 'のむ', meaning: 'to drink', type: 'u-verb'},
            {id: 2, word: '飲む', pronunciation: 'のむ', meaning: 'to drink', type: 'u-verb'}]
  },
  {
    username: 'kaijuking',
    deckname: 'Genki 1',
    source: 'ニュースの日本語',
    isbn: '978-4-7890-1596-7',
    publisher: 'The Japan Times',
    numcards: 2,
    description: 'A list of vocab from the Genki 1 book',
    createdon: 1459288249160,
    lastmodified: 1459288249160,
    cards: [{id: 1, word: '書く', pronunciation: 'かく', meaning: 'to write', type: 'u-verb'},
            {id: 2, word: '書く', pronunciation: 'かく', meaning: 'to write', type: 'u-verb'}]
  },
  {
    username: 'kaijuking',
    deckname: 'Genki 2',
    source: 'ニュースの日本語',
    isbn: '978-4-7890-1596-7',
    publisher: 'The Japan Times',
    numcards: 2,
    description: 'A list of vocab from the Genki 2 book',
    createdon: 1459288258457,
    lastmodified: 1459288258457,
    cards: [{id: 1, word: '読む', pronunciation: 'よむ', meaning: 'to read', type: 'u-verb'},
            {id: 2, word: '読む', pronunciation: 'よむ', meaning: 'to read', type: 'u-verb'}]
  },
  {
    username: 'kaijuking',
    deckname: 'Business Japanese',
    source: 'ニュースの日本語',
    isbn: '978-4-7890-1596-7',
    publisher: 'The Japan Times',
    numcards: 167,
    description: 'Business Japanese vocab',
    createdon: 1459288265978,
    lastmodified: 1459288265978,
    cards: [
      {id: 1, word: '伴う', pronunciation: 'ともなう', meaning: 'to eat', type: 'u-verb'},
      {id: 2, word: '新卒採用', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 3, word: '中途採用', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 4, word: '採用する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 5, word: '拡大する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 6, word: '縮小する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 7, word: '～倍', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 8, word: '見込み', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 9, word: '大卒', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 10, word: '高卒', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 11, word: '理系', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 12, word: '文系', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 13, word: '技術職', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 14, word: '事務職', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 15, word: '～枠', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 16, word: '計画する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 17, word: '希望者', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 18, word: '就職する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 19, word: '希望する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 20, word: '求人倍率', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 21, word: '売り手市場', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 22, word: '買い手市場', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 23, word: '募集する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 24, word: '応募する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 25, word: '既卒', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 26, word: '雇用する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 27, word: '就活', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 28, word: '就職活動', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 29, word: '状況', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 30, word: '面接する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 31, word: '人員削減', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 32, word: '削減する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 33, word: '対象', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 34, word: '希望退職', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 35, word: '退職する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 36, word: '規模', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 37, word: '見通し', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 38, word: '契約社員', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 39, word: '契約する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 40, word: '解雇する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 41, word: '再就職', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 42, word: '支援する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 43, word: '年功諸列', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 44, word: '終身雇用制度', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 45, word: '定年', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 46, word: '早期退職する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 47, word: '独立する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 48, word: '珍しくない', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 49, word: '起業する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 50, word: '結婚する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 51, word: '出産する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 52, word: '派遣社員', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 53, word: '派遣する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 54, word: '非正規', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 55, word: '賞与', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 56, word: 'ボーナス', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 57, word: '支給額', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 58, word: '支給する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 59, word: '労使交渉', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 60, word: '春闘', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 61, word: '春季逃走', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 62, word: '秋闘', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 63, word: '秋季逃走', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 64, word: '結果', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 65, word: '原因', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 66, word: '出そろう', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 67, word: '連続', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 68, word: '増加する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 69, word: '減少する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 70, word: '厚生労働省', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 71, word: '調査する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 72, word: '基本給', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 73, word: '維持する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 74, word: '妥結する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 75, word: '労組', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 76, word: '労働組合', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 77, word: '回答する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 78, word: '不服とする', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 79, word: '回避する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 80, word: '勤務する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 81, word: '平均給与', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 82, word: '残業する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 83, word: '残業代', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 84, word: '導入する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 85, word: 'フレックス制度', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 86, word: '柔軟化する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 87, word: '柔軟(な)', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 88, word: 'コアタイム', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 89, word: '満たす', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 90, word: '出勤する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 91, word: '退勤する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 92, word: '育児', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 93, word: '介護する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 94, word: '家庭', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 95, word: '両立する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 96, word: '就業規則', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 97, word: '変更する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 98, word: '始業', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 99, word: '終業', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 100, word: '可能(な)', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 101, word: '参加する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 102, word: '有給休暇', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 103, word: '人気が高い', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 104, word: '住宅手当', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 105, word: '福利厚生', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 106, word: '充実する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 107, word: '社員同士', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 108, word: '情報伝達', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 109, word: '円滑', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 110, word: '名刺', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 111, word: '名刺交換', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 112, word: '受け取る', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 113, word: '検索する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 114, word: '閲覧する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 115, word: '共有する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 116, word: '効果的な', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 117, word: '十分な', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 118, word: '異動する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 119, word: '赴任する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 120, word: '転勤する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 121, word: '同僚', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 122, word: '部下', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 123, word: '上司', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 124, word: 'WEB会議', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 125, word: '引き継ぐ', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 126, word: '難航する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 127, word: '異業種交流会', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 128, word: '盛んな', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 129, word: '都心', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 130, word: 'オフィス街', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 131, word: '開催する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 132, word: '地元', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 133, word: '勤める', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 134, word: '地区', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 135, word: '再開発', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 136, word: '壁を超える', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 137, word: '意見交換', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 138, word: '人脈作り', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 139, word: '役立てる', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 140, word: '商店街', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 141, word: '老舗', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 142, word: '創業者', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 143, word: '研修会', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 144, word: '講演会', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 145, word: '積極的な', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 146, word: '発表会', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 147, word: '展示会', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 148, word: '防災の日', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 149, word: '訓練する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 150, word: '実施する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 151, word: '震度', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 152, word: '地震', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 153, word: '発生する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 154, word: '想定する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 155, word: '避難する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 156, word: '確認する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 157, word: '初期消火', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 158, word: '消化する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 159, word: '帰宅困難者', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 160, word: '受け入れ態勢', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 161, word: '誘導する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 162, word: '非常食', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 163, word: '備蓄する', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 164, word: '火災', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 165, word: '設備', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 166, word: '安全対策', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'},
      {id: 167, word: '危機管理能力', pronunciation: 'しんそつさいよう', meaning: 'to eat', type: 'ru-verb'}
    ]
  },
  {
    username: 'kaijuking',
    deckname: 'Verbs',
    source: 'ニュースの日本語',
    isbn: '978-4-7890-1596-7',
    publisher: 'The Japan Times',
    numcards: 6,
    description: 'Common Verbs',
    createdon: 1459288265978,
    lastmodified: 1459288265978,
    cards: [{id: 1, word: '食べる', pronunciation: 'たべる', meaning: 'to eat', type: 'ru-verb'},
            {id: 2, word: '飲む', pronunciation: 'のむ', meaning: 'to drink', type: 'u-verb'},
            {id: 3, word: '書く', pronunciation: 'かく', meaning: 'to write', type: 'u-verb'},
            {id: 4, word: '読む', pronunciation: 'よむ', meaning: 'to read', type: 'u-verb'},
            {id: 5, word: '勉強する', pronunciation: 'べんきょうする', meaning: 'to study', type: 'ru-verb'},
            {id: 6, word: '就職する', pronunciation: 'しゅうしょくする', meaning: 'to get a job, to find employment', type: 'ru-verb'}]
  }
]

module.exports = decks;
