var decks = [
  {
    username: 'kaijuking',
    id: '1',
    deckname: 'JLPT N2 Verbs',
    source: 'ニュースの日本語',
    sourceimage: 'default2.jpg',
    isbn: '978-4-7890-1596-7',
    publisher: 'The Japan Times',
    numcards: 2,
    description: 'A list of JLPT N2 verbs',
    createdon: 1459288218005,
    lastmodified: 1459288218005,
    cards: [{id: 1, word: '食べる', pronunciation: 'たべる', meaning: 'to eat', type: 'ru-verb'},
            {id: 2, word: '食べる', pronunciation: 'たべる', meaning: 'to eat', type: 'ru-verb'}]
  },
  {
    username: 'kaijuking',
    id: '2',
    deckname: 'JLPT N2 Adjectives',
    source: 'ニュースの日本語',
    sourceimage: 'default2.jpg',
    isbn: '978-4-7890-1596-7',
    publisher: 'The Japan Times',
    numcards: 2,
    description: 'A list of JLPT N2 adjectives',
    createdon: 1459288235927,
    lastmodified: 1459288235927,
    cards: [{id: 1, word: '飲む', pronunciation: 'のむ', meaning: 'to drink', type: 'u-verb'},
            {id: 2, word: '飲む', pronunciation: 'のむ', meaning: 'to drink', type: 'u-verb'}]
  },
  {
    username: 'kaijuking',
    id:'3',
    deckname: 'Genki 1',
    source: 'ニュースの日本語',
    sourceimage: 'Genki1.jpg',
    isbn: '978-4-7890-1596-7',
    publisher: 'The Japan Times',
    numcards: 2,
    description: 'A list of vocab from the Genki 1 book',
    createdon: 1459288249160,
    lastmodified: 1459288249160,
    cards: [{id: 1, word: '書く', pronunciation: 'かく', meaning: 'to write', type: 'u-verb'},
            {id: 2, word: '書く', pronunciation: 'かく', meaning: 'to write', type: 'u-verb'}]
  },
  {
    username: 'kaijuking',
    id: '4',
    deckname: 'Genki 2',
    source: 'ニュースの日本語',
    sourceimage: 'Genki2.jpg',
    isbn: '978-4-7890-1596-7',
    publisher: 'The Japan Times',
    numcards: 2,
    description: 'A list of vocab from the Genki 2 book',
    createdon: 1459288258457,
    lastmodified: 1459288258457,
    cards: [{id: 1, word: '読む', pronunciation: 'よむ', meaning: 'to read', type: 'u-verb'},
            {id: 2, word: '読む', pronunciation: 'よむ', meaning: 'to read', type: 'u-verb'}]
  },
  {
    username: 'kaijuking',
    id:'5',
    deckname: 'Business Japanese',
    source: 'ニュースの日本語',
    sourceimage: 'NewsJapanese.jpg',
    isbn: '978-4-7890-1596-7',
    publisher: 'The Japan Times',
    numcards: 167,
    description: 'Business Japanese vocab',
    createdon: 1459288265978,
    lastmodified: 1459288265978,
    cards: [
      {id: 1, word: '伴う', pronunciation: 'ともなう', meaning: 'to associate with', type: 'u-verb'},
      {id: 2, word: '新卒採用', pronunciation: 'しんそつさいよう', meaning: 'hiring of new graduates', type: 'noun'},
      {id: 3, word: '中途採用', pronunciation: 'ちゅうとさいよう', meaning: 'mid-career recruitment', type: 'noun'},
      {id: 4, word: '採用する', pronunciation: 'さいようする', meaning: 'to hire', type: 'suru-verb'},
      {id: 5, word: '拡大する', pronunciation: 'かくだいする', meaning: 'to enlarge, magnify, increase', type: 'suru-verb'},
      {id: 6, word: '縮小する', pronunciation: 'しゅくしょうする', meaning: 'to decerease', type: 'suru-verb'},
      {id: 7, word: '～倍', pronunciation: '～ばい', meaning: '~times', type: 'noun'},
      {id: 8, word: '見込み', pronunciation: 'みこみ', meaning: 'probability', type: 'noun'},
      {id: 9, word: '大卒', pronunciation: 'だいそつ', meaning: 'college graduate', type: 'noun'},
      {id: 10, word: '高卒', pronunciation: 'こうそつ', meaning: 'high schoool graduate', type: 'noun'},
      {id: 11, word: '理系', pronunciation: 'りけい', meaning: 'the sciences', type: 'noun'},
      {id: 12, word: '文系', pronunciation: 'ぶんけい', meaning: 'the humanities', type: 'noun'},
      {id: 13, word: '技術職', pronunciation: 'ぎじゅつしょく', meaning: 'technical job', type: 'noun'},
      {id: 14, word: '事務職', pronunciation: 'じむしょく', meaning: 'clerical job', type: 'noun'},
      {id: 15, word: '～枠', pronunciation: '～わく', meaning: 'limit of~', type: 'noun'},
      {id: 16, word: '計画する', pronunciation: 'けいかくする', meaning: 'to plan', type: 'suru-verb'},
      {id: 17, word: '希望者', pronunciation: 'きぼうしゃ', meaning: 'applicant', type: 'noun'},
      {id: 18, word: '就職する', pronunciation: 'しゅうしょくする', meaning: 'to get a job', type: 'suru-verb'},
      {id: 19, word: '希望する', pronunciation: 'きぼうする', meaning: 'to hope, desire', type: 'suru-verb'},
      {id: 20, word: '求人倍率', pronunciation: 'きゅうじんばいりつ', meaning: 'application ratio', type: 'noun'},
      {id: 21, word: '売り手市場', pronunciation: 'うりてしじょう', meaning: 'a seller\'s market', type: 'noun'},
      {id: 22, word: '買い手市場', pronunciation: 'かいてしじょう', meaning: 'a buyer\'s market', type: 'noun'},
      {id: 23, word: '募集する', pronunciation: 'ぼしゅうする', meaning: 'to recruit', type: 'suru-verb'},
      {id: 24, word: '応募する', pronunciation: 'おうぼする', meaning: 'to apply', type: 'suru-verb'},
      {id: 25, word: '既卒', pronunciation: 'きそつ', meaning: 'graduate', type: 'noun'},
      {id: 26, word: '雇用する', pronunciation: 'こようする', meaning: 'to employ', type: 'suru-verb'},
      {id: 27, word: '就活', pronunciation: 'しゅうかつ', meaning: 'job hunting', type: 'noun'},
      {id: 28, word: '就職活動', pronunciation: 'しゅうしょくかつどう', meaning: 'job hunting', type: 'noun'},
      {id: 29, word: '状況', pronunciation: 'じょうきょう', meaning: 'situation', type: 'noun'},
      {id: 30, word: '面接する', pronunciation: 'めんせつする', meaning: 'to interview', type: 'suru-verb'},
      {id: 31, word: '人員削減', pronunciation: 'じんいんさくげん', meaning: 'downsizing', type: 'noun'},
      {id: 32, word: '削減する', pronunciation: 'さくげんする', meaning: 'to cut', type: 'suru-verb'},
      {id: 33, word: '対象', pronunciation: 'たいしょう', meaning: 'target', type: 'noun'},
      {id: 34, word: '希望退職', pronunciation: 'きぼうたいしょく', meaning: 'voluntary retirement', type: 'noun'},
      {id: 35, word: '退職する', pronunciation: 'たいしょくする', meaning: 'to leave a job, retire', type: 'suru-verb'},
      {id: 36, word: '規模', pronunciation: 'きぼ', meaning: 'scale', type: 'noun'},
      {id: 37, word: '見通し', pronunciation: 'みとおし', meaning: 'vision', type: 'noun'},
      {id: 38, word: '契約社員', pronunciation: 'けいやくしゃいん', meaning: 'contract employee', type: 'noun'},
      {id: 39, word: '契約する', pronunciation: 'けいやくする', meaning: 'to contract', type: 'suru-verb'},
      {id: 40, word: '解雇する', pronunciation: 'かいこする', meaning: 'to dismiss', type: 'suru-verb'},
      {id: 41, word: '再就職', pronunciation: 'さいしゅうしょく', meaning: 're-employment', type: 'noun'},
      {id: 42, word: '支援する', pronunciation: 'しえんする', meaning: 'to support', type: 'suru-verb'},
      {id: 43, word: '年功諸列', pronunciation: 'ねんこうじょれつ', meaning: 'seniority-based advancement', type: 'noun'},
      {id: 44, word: '終身雇用制度', pronunciation: 'しゅうしんこようせいど', meaning: 'lifetime employment', type: 'noun'},
      {id: 45, word: '定年', pronunciation: 'ていねん', meaning: 'retirement age', type: 'noun'},
      {id: 46, word: '早期退職する', pronunciation: 'そうきたいしょくする', meaning: 'to take early retirment', type: 'suru-verb'},
      {id: 47, word: '独立する', pronunciation: 'どくりつする', meaning: 'to go out on one\'s own, to be independent', type: 'suru-verb'},
      {id: 48, word: '珍しくない', pronunciation: 'めずらしくない', meaning: 'not uncommon', type: 'i-adjective'},
      {id: 49, word: '起業する', pronunciation: 'きぎょうする', meaning: 'to start one\'s own business', type: 'suru-verb'},
      {id: 50, word: '結婚する', pronunciation: 'けっこんする', meaning: 'to get married', type: 'suru-verb'},
      {id: 51, word: '出産する', pronunciation: 'しゅっさんする', meaning: 'to give birth', type: 'suru-verb'},
      {id: 52, word: '派遣社員', pronunciation: 'はけんしゃいん', meaning: 'temporary staff', type: 'noun'},
      {id: 53, word: '派遣する', pronunciation: 'はけんする', meaning: 'to dispatch', type: 'suru-verb'},
      {id: 54, word: '非正規', pronunciation: 'ひせいき', meaning: 'non-regular', type: 'noun'},
      {id: 55, word: '賞与', pronunciation: 'しょうよ', meaning: 'bonus', type: 'noun'},
      {id: 56, word: 'ボーナス', pronunciation: 'ぼーなす', meaning: 'bonus', type: 'noun'},
      {id: 57, word: '支給額', pronunciation: 'しきゅうがく', meaning: 'payment amount', type: 'noun'},
      {id: 58, word: '支給する', pronunciation: 'しきゅうする', meaning: 'to pay', type: 'suru-verb'},
      {id: 59, word: '労使交渉', pronunciation: 'ろうしこうしょう', meaning: 'labor negotiations', type: 'noun'},
      {id: 60, word: '春闘', pronunciation: 'しゅんとう', meaning: 'spring labor offensive', type: 'noun'},
      {id: 61, word: '春季闘争', pronunciation: 'しゅんきとうそう', meaning: 'spring labor offensive', type: 'noun'},
      {id: 62, word: '秋闘', pronunciation: 'しゅうとう', meaning: 'fall labor offensive', type: 'noun'},
      {id: 63, word: '秋季闘争', pronunciation: 'しゅうきとうそう', meaning: 'fall labor offensive', type: 'noun'},
      {id: 64, word: '結果', pronunciation: 'けっか', meaning: 'result', type: 'noun'},
      {id: 65, word: '原因', pronunciation: 'げんいん', meaning: 'cause', type: 'noun'},
      {id: 66, word: '出そろう', pronunciation: 'でそろう', meaning: 'to come out', type: 'u-verb'},
      {id: 67, word: '連続', pronunciation: 'れんそく', meaning: 'consecutive', type: 'noun'},
      {id: 68, word: '増加する', pronunciation: 'ぞうかする', meaning: 'to increase, rise', type: 'suru-verb'},
      {id: 69, word: '減少する', pronunciation: 'げんしょうする', meaning: 'to decrease, fall', type: 'suru-verb'},
      {id: 70, word: '厚生労働省', pronunciation: 'こうせいろうどうしょう', meaning: 'Ministry of Health, Labor and Welfare', type: 'noun'},
      {id: 71, word: '調査する', pronunciation: 'ちょうさする', meaning: 'to research', type: 'suru-verb'},
      {id: 72, word: '基本給', pronunciation: 'きほんきゅう', meaning: 'base salary', type: 'noun'},
      {id: 73, word: '維持する', pronunciation: 'いじする', meaning: 'to maintain', type: 'suru-verb'},
      {id: 74, word: '妥結する', pronunciation: 'だけつする', meaning: 'to reach an agreement', type: 'suru-verb'},
      {id: 75, word: '労組', pronunciation: 'ろうそ', meaning: 'labor union', type: 'noun'},
      {id: 76, word: '労働組合', pronunciation: 'ろうどうくみあい', meaning: 'labor union', type: 'noun'},
      {id: 77, word: '回答する', pronunciation: 'かいとうする', meaning: 'to give a reply', type: 'suru-verb'},
      {id: 78, word: '不服とする', pronunciation: 'ふふくとする', meaning: 'to express one\'s dissatisfaction', type: 'suru-verb'},
      {id: 79, word: '回避する', pronunciation: 'かいひする', meaning: 'to avoid', type: 'suru-verb'},
      {id: 80, word: '勤務する', pronunciation: 'きんむする', meaning: 'to work', type: 'suru-verb'},
      {id: 81, word: '平均給与', pronunciation: 'へいきんきゅうよ', meaning: 'average salary', type: 'noun'},
      {id: 82, word: '残業する', pronunciation: 'ざんぎょうする', meaning: 'to work overtime', type: 'suru-verb'},
      {id: 83, word: '残業代', pronunciation: 'ざんぎょうだい', meaning: 'overtime pay', type: 'noun'},
      {id: 84, word: '導入する', pronunciation: 'どうにゅうする', meaning: 'to adopt', type: 'suru-verb'},
      {id: 85, word: 'フレックス制度', pronunciation: 'ふれっくすせいど', meaning: 'flextime system', type: 'noun'},
      {id: 86, word: '柔軟化する', pronunciation: 'じゅうなんかする', meaning: 'to make flexible', type: 'suru-verb'},
      {id: 87, word: '柔軟(な)', pronunciation: 'じゅうなん(な)', meaning: 'flexible', type: 'na-adjective'},
      {id: 88, word: 'コアタイム', pronunciation: 'こあたいむ', meaning: 'core time', type: 'noun'},
      {id: 89, word: '満たす', pronunciation: 'みたす', meaning: 'to fulfill', type: 'u-verb'},
      {id: 90, word: '出勤する', pronunciation: 'しゅっきんする', meaning: 'to arrive for work', type: 'suru-verb'},
      {id: 91, word: '退勤する', pronunciation: 'たいきんする', meaning: 'to leave work', type: 'suru-verb'},
      {id: 92, word: '育児', pronunciation: 'いくじ', meaning: 'childcare', type: 'noun'},
      {id: 93, word: '介護する', pronunciation: 'かいごする', meaning: 'to care', type: 'suru-verb'},
      {id: 94, word: '家庭', pronunciation: 'かてい', meaning: 'home', type: 'noun'},
      {id: 95, word: '両立する', pronunciation: 'りょうりつする', meaning: 'to balance', type: 'suru-verb'},
      {id: 96, word: '就業規則', pronunciation: 'しゅうぎょうきそく', meaning: 'work regulations', type: 'noun'},
      {id: 97, word: '変更する', pronunciation: 'へんこうする', meaning: 'to change', type: 'suru-verb'},
      {id: 98, word: '始業', pronunciation: 'しぎょう', meaning: 'start work', type: 'noun'},
      {id: 99, word: '終業', pronunciation: 'しゅうぎょう', meaning: 'finish work', type: 'noun'},
      {id: 100, word: '可能(な)', pronunciation: 'かのう(な)', meaning: 'possible', type: 'na-ajective'},
      {id: 101, word: '参加する', pronunciation: 'さんかする', meaning: 'to participate', type: 'suru-verb'},
      {id: 102, word: '有給休暇', pronunciation: 'ゆうきゅうきゅうか', meaning: 'paid holiday', type: 'noun'},
      {id: 103, word: '人気が高い', pronunciation: 'にんきがたかい', meaning: 'popular', type: 'i-adjective'},
      {id: 104, word: '住宅手当', pronunciation: 'じゅうたくてあて', meaning: 'housing allowance', type: 'noun'},
      {id: 105, word: '福利厚生', pronunciation: 'ふくりこうせい', meaning: 'benefits package', type: 'noun'},
      {id: 106, word: '充実する', pronunciation: 'じゅうじつする', meaning: 'to fulfill', type: 'suru-verb'},
      {id: 107, word: '社員同士', pronunciation: 'しゃいんどうし', meaning: 'fellow employees', type: 'noun'},
      {id: 108, word: '情報伝達', pronunciation: 'じょうほうでんたつ', meaning: 'communication, information transfer', type: 'noun'},
      {id: 109, word: '円滑(な)', pronunciation: 'えんかつ(な)', meaning: 'smooth', type: 'na-adjective'},
      {id: 110, word: '名刺', pronunciation: 'めいし', meaning: 'business card', type: 'noun'},
      {id: 111, word: '名刺交換', pronunciation: 'めいしこうかん', meaning: 'exchange of business cards', type: 'noun'},
      {id: 112, word: '受け取る', pronunciation: 'うけとる', meaning: 'to receive, accept, take', type: 'u-verb'},
      {id: 113, word: '検索する', pronunciation: 'けんさくする', meaning: 'to search, lookup', type: 'suru-verb'},
      {id: 114, word: '閲覧する', pronunciation: 'えつらんする', meaning: 'to search, web browse', type: 'suru-verb'},
      {id: 115, word: '共有する', pronunciation: 'きゅうゆうする', meaning: 'to share', type: 'suru-verb'},
      {id: 116, word: '効果的(な)', pronunciation: 'こうかてき(な)', meaning: 'effective', type: 'na-adjective'},
      {id: 117, word: '十分(な)', pronunciation: 'じゅうぶん(な)', meaning: 'sufficient', type: 'na-adjective'},
      {id: 118, word: '異動する', pronunciation: 'いとうする', meaning: 'to move', type: 'suru-verb'},
      {id: 119, word: '赴任する', pronunciation: 'ふにんする', meaning: 'to take one\'s post', type: 'suru-verb'},
      {id: 120, word: '転勤する', pronunciation: 'てんきんする', meaning: 'to transfer', type: 'suru-verb'},
      {id: 121, word: '同僚', pronunciation: 'どうりょう', meaning: 'co-worker, colleague', type: 'noun'},
      {id: 122, word: '部下', pronunciation: 'ぶか', meaning: 'subordinate', type: 'noun'},
      {id: 123, word: '上司', pronunciation: 'じょうし', meaning: 'superior', type: 'noun'},
      {id: 124, word: 'WEB会議', pronunciation: 'WEBかいぎ', meaning: 'WEB meeting', type: 'noun'},
      {id: 125, word: '引き継ぐ', pronunciation: 'ひきつぐ', meaning: 'to take over', type: 'u-verb'},
      {id: 126, word: '難航する', pronunciation: 'なんこうする', meaning: 'to become heavy going', type: 'suru-verb'},
      {id: 127, word: '異業種交流会', pronunciation: 'いぎょうしゅこうりゅうかい', meaning: 'cross-industry social event', type: 'noun'},
      {id: 128, word: '盛ん(な)', pronunciation: 'さかん(な)', meaning: 'active, prosperous, popular', type: 'na-adjective'},
      {id: 129, word: '都心', pronunciation: 'としん', meaning: 'city center', type: 'noun'},
      {id: 130, word: 'オフィス街', pronunciation: 'おふぃすがい', meaning: 'business district', type: 'noun'},
      {id: 131, word: '開催する', pronunciation: 'かいさいする', meaning: 'to convene', type: 'suru-verb'},
      {id: 132, word: '地元', pronunciation: 'じもと', meaning: 'the local area', type: 'noun'},
      {id: 133, word: '勤める', pronunciation: 'つとめる', meaning: 'to work', type: 'u-verb'},
      {id: 134, word: '地区', pronunciation: 'ちく', meaning: 'district', type: 'noun'},
      {id: 135, word: '再開発', pronunciation: 'さいかいはつ', meaning: 'redevelopment', type: 'noun'},
      {id: 136, word: '壁を超える', pronunciation: 'かべをこえる', meaning: 'to break the barrier', type: 'u-verb'},
      {id: 137, word: '意見交換', pronunciation: 'いけんこうかん', meaning: 'exchange of opinions', type: 'noun'},
      {id: 138, word: '人脈作り', pronunciation: 'じんみゃくづくり', meaning: 'networking', type: 'noun'},
      {id: 139, word: '役立てる', pronunciation: 'やくだてる', meaning: 'to put to use, make use of', type: 'ru-verb'},
      {id: 140, word: '商店街', pronunciation: 'しょうてんがい', meaning: 'shopping district', type: 'noun'},
      {id: 141, word: '老舗', pronunciation: 'しにせ', meaning: 'long established store', type: 'noun'},
      {id: 142, word: '創業者', pronunciation: 'そうぎょうしゃ', meaning: 'founder', type: 'noun'},
      {id: 143, word: '研修会', pronunciation: 'けんしゅうかい', meaning: 'workshop', type: 'noun'},
      {id: 144, word: '講演会', pronunciation: 'こうえんがい', meaning: 'lecture meeting', type: 'noun'},
      {id: 145, word: '積極的(な)', pronunciation: 'せっきょくてき(な)', meaning: 'assertive, positive, active, proactive', type: 'na-adjective'},
      {id: 146, word: '発表会', pronunciation: 'はっぴょうかい', meaning: 'presentation, announcement meeting', type: 'noun'},
      {id: 147, word: '展示会', pronunciation: 'てんじかい', meaning: 'exhibition', type: 'noun'},
      {id: 148, word: '防災の日', pronunciation: 'ぼうさいのひ', meaning: 'National Disaster Prevention Day', type: 'noun'},
      {id: 149, word: '訓練する', pronunciation: 'くんれんする', meaning: 'to train', type: 'suru-verb'},
      {id: 150, word: '実施する', pronunciation: 'じっしする', meaning: 'to conduct, carry out, enforce, put into practice', type: 'suru-verb'},
      {id: 151, word: '震度', pronunciation: 'しんど', meaning: 'earthquake magnitude', type: 'noun'},
      {id: 152, word: '地震', pronunciation: 'じしん', meaning: 'earthquake', type: 'noun'},
      {id: 153, word: '発生する', pronunciation: 'はっせいする', meaning: 'to occur, outbreak', type: 'suru-verb'},
      {id: 154, word: '想定する', pronunciation: 'そうていする', meaning: 'to assume, suppose, hypothesize', type: 'suru-verb'},
      {id: 155, word: '避難する', pronunciation: 'ひなんする', meaning: 'to evacuate', type: 'suru-verb'},
      {id: 156, word: '確認する', pronunciation: 'かくにんする', meaning: 'to verify, confirm', type: 'suru-verb'},
      {id: 157, word: '初期消火', pronunciation: 'しょきしょうか', meaning: 'early fire extinguishing', type: 'noun'},
      {id: 158, word: '消化する', pronunciation: 'しょうかする', meaning: 'to put out a fire', type: 'suru-verb'},
      {id: 159, word: '帰宅困難者', pronunciation: 'きたくこんんあんしゃ', meaning: 'people who are unable to return home', type: 'noun'},
      {id: 160, word: '受け入れ態勢', pronunciation: 'うけいれたいせい', meaning: 'preparation to receive', type: 'noun'},
      {id: 161, word: '誘導する', pronunciation: 'ゆうどうする', meaning: 'to lead, to guide', type: 'ru-verb'},
      {id: 162, word: '非常食', pronunciation: 'ひじょうしょく', meaning: 'emergency food', type: 'food'},
      {id: 163, word: '備蓄する', pronunciation: 'びちくする', meaning: 'to stock', type: 'ru-verb'},
      {id: 164, word: '火災', pronunciation: 'かさい', meaning: 'fire', type: 'noun'},
      {id: 165, word: '設備', pronunciation: 'せつび', meaning: 'equipment, device', type: 'noun'},
      {id: 166, word: '安全対策', pronunciation: 'あんぜんたいさく', meaning: 'safety measures', type: 'noun'},
      {id: 167, word: '危機管理能力', pronunciation: 'ききかんりのうりょく', meaning: 'crisis management abilities', type: 'noun'}
    ]
  },
  {
    username: 'kaijuking',
    id: '6',
    deckname: 'Verbs',
    source: 'ニュースの日本語',
    sourceimage: 'default2.jpg',
    isbn: '978-4-7890-1596-7',
    publisher: 'The Japan Times',
    numcards: 6,
    description: 'Common Verbs',
    createdon: 1459288265978,
    lastmodified: 1459288265978,
    cards: [{id: 1, word: '食べる', pronunciation: 'たべる', meaning: 'to eat', type: 'ru-verb'},
            {id: 2, word: '飲む', pronunciation: 'のむ', meaning: 'to drink', type: 'u-verb'},
            {id: 3, word: '書く', pronunciation: 'かく', meaning: 'to write', type: 'u-verb'},
            {id: 4, word: '読む', pronunciation: 'よむ', meaning: 'to read', type: 'u-verb'},
            {id: 5, word: '勉強する', pronunciation: 'べんきょうする', meaning: 'to study', type: 'suru-verb'},
            {id: 6, word: '就職する', pronunciation: 'しゅうしょくする', meaning: 'to get a job, to find employment', type: 'suru-verb'}]
  }
]

module.exports = decks;
